upstream django_app {
    server web:8000;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://django_app;
        # Pass the true IP and host metadata so Django can validate cookies securely
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
    
        # Ensures Nginx passes along cookie buffers properly
        proxy_pass_header Set-Cookie;
        
        proxy_redirect off;
    }

    # Optional: If you handle static files, Nginx can serve them directly
    location /static/ {
        alias /app/staticfiles/;
    }
}